services:
    group.topic_counters_listener:
        class: GroupBundle\EventListener\TopicCountersSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    group.group_counters_listener:
        class: GroupBundle\EventListener\GroupCountersSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    group.user_counters_subscriber:
        class: GroupBundle\EventListener\UserCountersSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    group.topic_voter:
        class: GroupBundle\Security\TopicVoter
        public: false
        tags:
            - { name: security.voter }

    group.comment_voter:
        class: GroupBundle\Security\CommentVoter
        public: false
        tags:
            - { name: security.voter }

    group.topic_twig_extension:
        class: GroupBundle\Twig\TopicExtension
        arguments: ['@security.authorization_checker']
        public: false
        tags:
            - { name: twig.extension }

    group.comment_twig_extension:
        class: GroupBundle\Twig\CommentExtension
        arguments: ['@security.authorization_checker']
        public: false
        tags:
            - { name: twig.extension }
