app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

group:
    resource: "@GroupBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

