services:
    user.authentication_subscriber:
        class: UserBundle\EventListener\AuthenticationSubscriber
        arguments: ['@security.authentication.manager', '@security.token_storage', 'main']
        tags:
            - { name: kernel.event_subscriber }

    user.interactive_login_subscriber:
        class: UserBundle\EventListener\LastLoginSubscriber
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }

    user.contains_reserved_words_validator:
        class: UserBundle\Validator\Constraints\ReservedWordsValidator
        arguments: ['@service_container']
        tags:
            - { name: validator.constraint_validator }