services:
    app.html_purifier:
        class: AppBundle\Utils\HTMLPurifier

    app.markdown:
        class: AppBundle\Utils\Markdown
        arguments: ['@app.html_purifier']

    app.twig.html_purifier_extension:
        class: AppBundle\Twig\HTMLPurifierExtension
        arguments: ['@app.html_purifier']
        public: false
        tags:
            - { name: twig.extension }

    app.twig.markdown_extension:
        class: AppBundle\Twig\MarkdownExtension
        arguments: ['@app.markdown']
        public: false
        tags:
            - { name: twig.extension }

    pagerfanta.view.twitter_bootstrap4:
        class: Pagerfanta\View\TwitterBootstrap4View
        public: false
        tags:
            - { name: pagerfanta.view, alias: twitter_bootstrap4 }

    pagerfanta.view.twitter_bootstrap4_translated:
        class: WhiteOctober\PagerfantaBundle\View\TwitterBootstrap3TranslatedView
        arguments: ['@pagerfanta.view.twitter_bootstrap4', '@translator']
        public: false
        tags:
            - { name: pagerfanta.view, alias: twitter_bootstrap4_translated }