services:
    app.html_purifier:
        class: AppBundle\Utils\HtmlPurifier

    app.twig.html_purifier_extension:
        class: AppBundle\Twig\HtmlPurifierExtension
        arguments: ['@app.html_purifier']
        public: false
        tags:
            - { name: twig.extension }