services:
    app.html_purifier:
        class: AppBundle\Utils\HTMLPurifier

    app.markdown:
        class: AppBundle\Utils\Markdown
        arguments: ['@app.html_purifier']

    app.twig.html_purifier_extension:
        class: AppBundle\Twig\HTMLPurifierExtension
        arguments: ['@app.html_purifier']
        public: false
        tags:
            - { name: twig.extension }

    app.twig.markdown_extension:
        class: AppBundle\Twig\MarkdownExtension
        arguments: ['@app.markdown']
        public: false
        tags:
            - { name: twig.extension }